version: "3.8"

services:

  carrier-service:
    image: antoniobello09/carrier-service:1.0.0
    container_name: carrierserviceimage
    ports:
      - 8081:8080
      - 8000:8000
    depends_on:
      - carrier-service-db
    networks:
      - shared-net

  carrier-service-db:
    image: mongo:5.0
    container_name: carrierservicemongodbimage
    ports:
      - 27018:27017
    networks:
      - shared-net

networks:
  shared-net:
    external: true