spring.application.name=carrier_management_service
spring.data.mongodb.host=carrier-service-db
spring.data.mongodb.port=27017
spring.data.mongodb.database=carrierdatabase

spring.rabbitmq.addresses=amqp://guest:guest@rabbitmq-container:5672
#spring.rabbitmq.addresses=amqp://guest:guest@172.31.42.140:5672
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.tuo.package=DEBUG
google.maps.api.key=OK
